accounts/urls.py
"""Degines urls for accounts Blog site."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [

    # Include default auth urls.

    path('', include('django.contrib.auth.urls')),

    #Registration page.

    path('register/', views.register, name='register')
]

blog/urls.py
"""Defines URL patterns for blog."""

from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [

    #Home page
    path('', views.index, name = 'index'),

    #All posts page

    path('all_posts', views.all_posts, name = 'all_posts'),

    #Post page
    path('<int:post_title>/', views.post, name = 'post'),

    #Page for add news posts.
    path('new_post/', views.new_post, name = 'new_post'),

    #Page for the texts.
    path('new_post_text/<int:post_title>/', views.new_post_text, name = 'new_post_text'),

    #Page for editing texts.
    path('edit_text/<int:posttext_id>/', views.edit_text, name = 'edit_text'),
]

bp_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    #My urls patterns.

    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BlogTitle(models.Model):

    """A space to add a title for the overall blog."""

    title_text = models.CharField(max_length = 200)

    pub_date = models.DateTimeField(auto_now_add = True)

    def __str__(self):

        return self.title_text.title()
    
class BlogText(models.Model):

    """This is where you put the text for the home page."""

    title = models.ForeignKey(BlogTitle, on_delete = models.CASCADE)

    text = models.TextField()

    pub_date = models.DateTimeField(auto_now_add = True)

    def __str__(self):

        if len(self.text) > 50:

            return f"{self.text[:50]}..."
            
        else:

            return f"{self.text[:50]}"
        
# ---------------------------------------------------------------------------- #
        
class PostTitle(models.Model):

    """A place to make posts in the blog."""

    post_title_text = models.CharField(max_length = 200)

    pub_date = models.DateTimeField(auto_now_add = True)

    holder = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):

        return self.post_title_text.title()
    
class PostText(models.Model):

    """Here we'll have the content."""

    post_title = models.ForeignKey(PostTitle, on_delete = models.CASCADE)

    text = models.TextField()

    pub_date = models.DateTimeField(auto_now_add = True)

    def __str__(self):

        if len(self.text) > 50:

            return f"{self.text[:50]}..."
            
        else:

            return f"{self.text[:50]}"

blog/forms.py
from django import forms

from .models import PostTitle, PostText

class PostTitleForm(forms.ModelForm):

    class Meta:

        model = PostTitle

        fields = ['post_title_text']
        labels = {'post_title_text' : ''}

class TextForm(forms.ModelForm):

    class Meta:

        model = PostText

        fields = ['text']
        labels = {'text' : ''}
        widgets = {'text' : forms.Textarea(attrs={'cols' : 80})}
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):

    """Register new users."""

    if request.method != 'POST':

        #Blank form for registration

        form = UserCreationForm()

    else:

        form = UserCreationForm(data=request.POST)

        #Process the data.

        if form.is_valid():

            #Make a new user.

            new_user = form.save()
        
            login(request, new_user)

            return redirect('blog:index')
        
    #Display a blank or invalid form.
        
    context = {'form' : form}

    return render(request, 'registration/register.html', context)

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.

from .models import BlogTitle, BlogText
from .models import PostTitle, PostText

from .forms import PostTitleForm, TextForm

# Functions.

def check_topic_owner(object, request):

    """Make sure the topic belongs to the current user."""

    from django.http import Http404

    if object.holder != request.user:

        raise Http404
    
# Views.

def index(request):

    """Home page."""

    return render(request, 'blog/index.html')

@login_required
def all_posts(request):

    """View for the Blog's Posts Page."""

    posts = PostTitle.objects.filter(holder=request.user.id).order_by('pub_date')

    context = {'posts' : posts}

    return render (request, 'blog/all_posts.html', context)

@login_required
def post(request, post_title):

    """View for a single post."""

    post = PostTitle.objects.get(id = post_title)
    texts = post.posttext_set.order_by('pub_date')

    # Verification
    check_topic_owner(post, request)

    context = {'post' : post, 'texts' : texts}

    return render (request, 'blog/post.html', context)

@login_required
def new_post(request):

    """Add a new post."""

    if request.method != 'POST':

        form = PostTitleForm()

    else:

        form = PostTitleForm(data = request.POST)

        if form.is_valid():

            new_post = form.save(commit=False)
            new_post.holder = request.user
            new_post.save()
            return redirect('blog:index')
        
    context = {'form' : form}

    return render(request, 'blog/new_post.html', context)

@login_required
def new_post_text(request, post_title):

    post = PostTitle.objects.get(id = post_title)

    if request.method != 'POST':

        form = TextForm()

    else:

        form = TextForm(data=request.POST)

        if form.is_valid():

            new_posttext= form.save(commit=False)
            new_posttext.post_title = post
            new_posttext.save()

            return redirect('blog:post', post_title = post_title)
        
    context = {'post' : post, 'form' : form}

    return render(request, 'blog/new_post_text.html', context)

@login_required
def edit_text(request, posttext_id):

    text = PostText.objects.get(id = posttext_id)
    title = text.post_title

    # Verification
    check_topic_owner(title, request)

    if request.method != 'POST':

        form = TextForm(instance = text)

    else:

        form = TextForm(instance = text, data = request.POST)

        if form.is_valid():

            form.save()
            return redirect ('blog:post', post_title = title.id)

    context = {'text' : text, 'title' : title, 'form' : form}
    return render(request, 'blog/edit_text.html', context)

blog/templates/blog/all_posts.html
{% extends 'blog/base.html' %}

{% block content %}

<p> Posts: </p>

<u>
    {% for post in posts %}

        <li><a href="{% url 'blog:post' post.id %}"> {{ post }} </a></li>

        <p></p>

    {% empty %}

        <li> No posts added yet. </li>

    {% endfor %}

</u>

<a href="{% url 'blog:new_post' %}"> Create a new post </a>

{% endblock content %}

blog/templates/blog/base.html
<p>

    <a href="{% url 'blog:index' %}"> Blog Home Page </a> -

    <a href="{% url 'blog:all_posts' %}"> Posts </a> -

    {% if user.is_authenticated %}

        Wellcome, {{ user.username }}.

    {% else %}

        <a href="{% url 'accounts:login' %}">Login</a> - 
        <a href="{% url 'accounts:register' %}">Register</a>

    {% endif %}
    
</p>

{% block content %}{% endblock content %}

{% if user.is_authenticated %}

<hr/>

    <form action="{% url 'accounts:logout' %}" method="post">

        {% csrf_token %}

        <button name="submit">Logot</button>

    </form>

{% endif %}

blog/templates/blog/edit_text.html
{% extends 'blog/base.html' %}

{% block content %}

<p><a href="{% url 'blog:post' title.id %}"> {{ title }}</a></p>

<p>Edit text:</p>

<form action="{% url 'blog:edit_text' text.id %}" method="post"> 

    {% csrf_token %}
    {{ form.as_div }}

    <button name="submit">Save Changes</button>

</form>

{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}

<p> Game Blog </p>

<p> A blog about games you ever played, share your experience. </p>

{% endblock content %}

blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}

{% block content %}

<p> Add a new Post: </p>

    <form action="{% url 'blog:new_post' %}" method = 'post'>

        {% csrf_token %}

        {{ form.as_div }}

        <button name="submit">Save Post</button>

    </form>

{% endblock content %}

blog/templates/blog/new_post_text.html
{% extends 'blog/base.html' %}

{% block content %}

<p><a href="{% url 'blog:post' post.id %}"> {{ post }}</a></p>

<p>Add a new text: </p>

    <form action="{% url 'blog:new_post_text' post.id %}" method="post">

        {% csrf_token %}

        {{ form.as_div }}
        
        <button name="submit"> Save Text </button>

    </form>

{% endblock content %}

blog/templates/blog/post.html
{% extends 'blog/base.html' %}

{% block content %}

<p> Title: {{ post.post_title_text }}</p>

<a href="{% url 'blog:new_post_text' post.id %}"> Create a new text </a>

<p> Posts: </p>

<ul>

    {% for text in texts %}

        <li>

            <p> {{ text.pub_date|date:'d/m/Y, H:i' }} </p>

            <p> {{ text.text|linebreaks }} </p>

            <p><a href="{% url 'blog:edit_text' text.id %}">Edit text</a></p>

        </li>

    {% empty %}

        <li> No posts added yet. </li>

    {% endfor %}

</ul>

{% endblock content %}